# Generated by Django 5.2.5 on 2026-02-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.CharField(max_length=100)),
                ('contenido', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('campos', models.JSONField()),
            ],
        ),
    ]
