# Generated by Django 5.2.5 on 2026-02-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datonegocio',
            options={'ordering': ['negocio', '-id'], 'verbose_name': 'Dato de Negocio', 'verbose_name_plural': 'Datos de Negocios'},
        ),
        migrations.AlterModelOptions(
            name='esquemanegocio',
            options={'ordering': ['nombre'], 'verbose_name': 'Esquema de Negocio', 'verbose_name_plural': 'Esquemas de Negocios'},
        ),
        migrations.AddField(
            model_name='datonegocio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datonegocio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='datonegocio',
            index=models.Index(fields=['negocio'], name='api_datoneg_negocio_20b218_idx'),
        ),
    ]
